- name: Add apt signing key for Kubernetes
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install kubernetes
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes

- name: Remove swapfile
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Configure node ip
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
    create: yes

- name: Setup iptables bridging
  ansible.builtin.shell: |
    cat <<EOF | tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF
    sudo echo '1' > /proc/sys/net/ipv4/ip_forward
    sudo sysctl --system

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
