- name: Initialize kubernetes cluster
  ansible.builtin.shell: |
    sudo modprobe overlay
    sudo modprobe br_netfilter
    sudo kubeadm init --service-dns-domain=danhable.local --node-name control-plane --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}"

- name: Configure ssh user environment settings
  remote_user: vagrant
  ansible.builtin.shell: |
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config
    kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null

- name: Set calicoctl Environment Variables
  ansible.builtin.lineinfile:
    path: /home/vagrant/.bashrc
    line: "{{ item }}"
  loop:
    - export KUBECONFIG=~/.kube/config
    - export DATASTORE_TYPE=kubernetes

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command

- name: Create local file with join command
  local_action: ansible.builtin.copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command.sh"
  become: no