packages:
  common:
    - curl
    - gcc
    - make
    - python
    - bash-completion
  redhat:
  debian:
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common